theme:
  switch: true
  default: style-dark

assets:
  internal_provider: local
  third_party_provider: https://npm.elemecdn.com

cdn:
  js:
    defer: /_vercel/insights/script.js

# favicon:
#   logo: favicon-32x32.png
#   icon16: favicon-16x16.png
#   icon32: favicon-32x32.png
#   appleTouchIcon: apple-touch-icon.png
#   webmanifest: /site.webmanifest

user:
  name: negoces
  first_name: Sai
  last_name: Kingyo
  email: nego@nekodayo.top
  domain: https://nekodayo.top
  avatar: /img/avatar.jpg
  describe: 现实中我们用真名说假话，网络中我们用假名说真话
  ruleText: 朋友多多，欢乐多多

banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!

top_bars:
  - title: home
    url: /
    # children:
    #   - title: archives2
    #     url: /archives2/
  - title: archives
    url: /archives/
    children:
      - title: categories
        url: /categories/
      - title: tags
        url: /tags/
    # noswup: true
  - title: links
    url: /links/
  - title: about
    url: /about/

sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/negoces
  typedTextPrefix: I`m
  typedText: ["Arch Linux User", "Debian User"]
  info: # 个人信息
    - key: Country
      val: China
    - key: Age
      val: 403 Forbidden

toc:
  enable: true
  list_number: true
  max_depth: 3
  min_depth: 1

lazyload:
  enable: true

archive:
  type: more

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: false

post_pagination:
  enable: true
  type: small

datetime_foramt:
  post_card:
    date: YYYY/MM/DD
    time: HH:mm
  post_info:
    date: YYYY/MM/DD
    time: HH:mm
  archive:
    date: YYYY/MM/DD
    time: HH:mm

notice_outdate:
  enable: true
  style: flat
  limit_day: 90
  position: top

rightside:
  readmode: true
  aside: true

footer:
  powered:
    enable: false
  beian:
    enable: false
    icp:
  copyrightYear: 2020
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 01/01/2020 00:00:00
  custom_text:

reward:
  enable: true
  comment: <del> 我很可爱 请给我钱 </del>
  methods:
    - name: 支付宝
      path: avatar.png

highlight:
  theme: true
  title: mac
  copy: true
  lang: true
  code_word_wrap: fasle
  height_limit: 200 # 超出时，显示折叠按钮

katex:
  copy_tex: true
  global: true
  options: {}

search:
  enable: true
  type: local
  preload: fasle
  trigger: auto

comment:
  giscus:
    enable: true
    repo: negoces/hexo-blog
    repo-id: R_kgDOKACK3w
    category: General
    category-id: DIC_kwDOKACK384CYJV3
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    input-position: top
    loading: lazy
    lang: zh-CN
    theme:
      light: light
      dark: dark
